# Generated by Django 5.0 on 2025-01-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250103_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='solardate',
            name='extra_day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solardate',
            name='is_extra_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solardate',
            name='gregorian_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solardate',
            name='solar_month',
            field=models.CharField(max_length=50),
        ),
    ]
