# Generated by Django 5.0 on 2025-01-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solardate_extra_day_number_solardate_is_extra_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardate',
            name='solar_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solardate',
            name='solar_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
