# Generated by Django 5.0 on 2025-01-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_options_alter_event_biblical_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_holy_day',
            field=models.BooleanField(default=False, verbose_name='Dia de Shabbat'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='is_holy_day',
            field=models.BooleanField(default=False, verbose_name='Dia de Shabbat'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(4, 'Sexta-feira'), (5, 'Sábado')], null=True, verbose_name='Dia da Semana'),
        ),
    ]
