# Generated by Django 5.0 on 2025-01-03 22:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiblicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Referência Bíblica',
                'verbose_name_plural': 'Referências Bíblicas',
                'ordering': ['book', 'chapter'],
            },
        ),
        migrations.CreateModel(
            name='SolarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian_date', models.DateField(unique=True)),
                ('solar_day', models.IntegerField()),
                ('solar_month', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['gregorian_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gregorian_date', models.DateField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('festival', 'Festival Bíblico'), ('historical', 'Evento Histórico'), ('sabbath', 'Shabat'), ('new_month', 'Rosh Chodesh'), ('equinox', 'Equinócio'), ('solstice', 'Solstício'), ('tekufah', 'Tekufah')], default='historical', max_length=20)),
                ('is_holy_day', models.BooleanField(default=False, verbose_name='Dia Santo')),
                ('sunset_start', models.BooleanField(default=True, verbose_name='Começa no Pôr do Sol')),
                ('biblical_references', models.ManyToManyField(blank=True, to='core.biblicalreference')),
                ('solar_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.solardate')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['gregorian_date', 'event_type'],
            },
        ),
    ]
