# Generated by Django 5.0 on 2025-01-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(blank=True, help_text='Cor para exibição no calendário (ex: #FF0000)', max_length=20, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, help_text='Emoji ou código do ícone', max_length=20, verbose_name='Ícone')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição no calendário', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['gregorian_date'], 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='biblical_references',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.biblicalreference', verbose_name='referências bíblicas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('festival', 'Festival Bíblico'), ('historical', 'Evento Histórico'), ('sabbath', 'Shabat'), ('new_month', 'Rosh Chodesh'), ('equinox', 'Equinócio'), ('solstice', 'Solstício'), ('tekufah', 'Tekufah')], default='historical', max_length=50, verbose_name='tipo de evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gregorian_date',
            field=models.DateField(verbose_name='data gregoriana'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_holy_day',
            field=models.BooleanField(default=False, verbose_name='dia santo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='solar_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.solardate', verbose_name='data solar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sunset_start',
            field=models.BooleanField(default=False, verbose_name='começa no pôr do sol'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventtype', verbose_name='tipo de evento'),
        ),
    ]
