# Generated by Django 5.0 on 2025-01-04 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventtype_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['gregorian_date', 'title'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='biblical_references',
            field=models.ManyToManyField(blank=True, to='core.biblicalreference', verbose_name='Referências Bíblicas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('festival', 'Festival Bíblico'), ('historical', 'Evento Histórico'), ('sabbath', 'Shabat'), ('new_month', 'Rosh Chodesh'), ('equinox', 'Equinócio'), ('solstice', 'Solstício'), ('tekufah', 'Tekufah')], default='historical', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventtype', verbose_name='Novo Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gregorian_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Gregoriana'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_holy_day',
            field=models.BooleanField(default=False, verbose_name='Dia Santo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='solar_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.solardate', verbose_name='Data Solar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sunset_start',
            field=models.BooleanField(default=True, verbose_name='Começa no Pôr do Sol'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Semanal'), ('annual', 'Anual'), ('lunar', 'Lunar')], max_length=10, verbose_name='Tipo de Recorrência')),
                ('weekday', models.IntegerField(blank=True, choices=[(5, 'Sexta-feira'), (6, 'Sábado')], null=True, verbose_name='Dia da Semana')),
                ('annual_month', models.IntegerField(blank=True, null=True, verbose_name='Mês')),
                ('annual_day', models.IntegerField(blank=True, null=True, verbose_name='Dia')),
                ('event_type', models.CharField(choices=[('festival', 'Festival Bíblico'), ('historical', 'Evento Histórico'), ('sabbath', 'Shabat'), ('new_month', 'Rosh Chodesh'), ('equinox', 'Equinócio'), ('solstice', 'Solstício'), ('tekufah', 'Tekufah')], default='historical', max_length=20, verbose_name='Tipo de Evento')),
                ('is_holy_day', models.BooleanField(default=False, verbose_name='Dia Santo')),
                ('sunset_start', models.BooleanField(default=True, verbose_name='Começa no Pôr do Sol')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='Última Geração')),
                ('biblical_references', models.ManyToManyField(blank=True, to='core.biblicalreference', verbose_name='Referências Bíblicas')),
                ('event_type_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtype', verbose_name='Novo Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento Recorrente',
                'verbose_name_plural': 'Eventos Recorrentes',
                'ordering': ['title'],
            },
        ),
    ]
